# Generated by Django 4.2.1 on 2023-10-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0002_alter_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="user_groups",
            field=models.ManyToManyField(blank=True, to="auth.group"),
        ),
    ]
