# Generated by Django 4.2.1 on 2023-11-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="user_groups",
        ),
        migrations.AddField(
            model_name="profile",
            name="position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "admin"),
                    ("manager", "manager"),
                    ("employee", "employee"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
