# Generated by Django 4.2.1 on 2023-11-06 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_alter_task_assignee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="user",
        ),
    ]
